Advanced repo management
opentelekomcloud-infra/gitstyring pull request #2
Opened 2020-11-25 11:46 UTC by anton-sidelnikov

2020-11-26 12:43 UTC, lego963 requested changes

2020-11-26 12:43 UTC, lego963 commented on orgs/opentelekomcloud-infra/repositories/test-to-be-deleted.yml
>          require_code_owner_reviews: false
`require_code_owner_reviews: false` let's make it true

2020-11-26 12:43 UTC, lego963 commented on roles/gitcontrol/default/main.yml
>  github_repos__state:
these vars `github_repo*` has `__`. Is it ok?

2020-11-26 13:26 UTC, outcatcher requested changes

2020-11-26 13:26 UTC, outcatcher commented on orgs/opentelekomcloud-infra/repositories/gitstyring.yml
> +      - csm
Maybe `eco`?

2020-11-26 13:26 UTC, outcatcher commented on playbooks/library/scan_organizations.py
> +            parsed_yaml_file = yaml.load(a_yaml_file, Loader=yaml.BaseLoader)
Maybe use `SafeLoader` or `yaml.safe_load`?

2020-11-26 13:26 UTC, outcatcher commented on roles/gitcontrol/files/github_api.py
> +        data = yaml.load(file, Loader=yaml.FullLoader)
Why are you using `FullLoader`?

2020-11-26 13:26 UTC, outcatcher commented on roles/gitcontrol/files/github_api.py
>      for clb in collaborators:
You can use `key, val in collaborators.items()` to iterate through both keys an values

2020-11-26 13:26 UTC, outcatcher commented on roles/gitcontrol/files/github_api.py
> +    for team in teams:
Same as previous

2020-11-26 13:26 UTC, outcatcher commented on roles/gitcontrol/files/github_api.py
> +        if teams[team]:
You can use 
```python
if not teams[team]:
    continue
```
to decrease indentation :)

2020-11-26 13:26 UTC, outcatcher commented on roles/gitcontrol/files/github_api.py
> +    branch_name = (list(rules.keys())[0])
Can be simmplified to `list(rules)[0]`

2020-11-26 13:28 UTC, outcatcher commented
recheck

2020-11-26 17:40 UTC, outcatcher commented on README.md
>      maintain:
What does `maintain` permissions mean?

2020-11-27 08:13 UTC, Polina-Gubina approved these changes

2020-11-27 08:14 UTC, lego963 submitted a review, later dismissed

2020-11-27 08:30 UTC, lego963 approved these changes

2020-11-27 08:36 UTC, irina-pereiaslavskaia approved these changes

2020-11-27 08:46 UTC, outcatcher approved these changes

2020-11-27 08:46 UTC, merged